version: "str"
only_goloop: false
required:
  env: true
  icon2: false
  iiss: false # for MainNet ( Custom is true )
  genesis: true
settings:
  env: {}
  genesis: null
  genesis_json: "/goloop/config/genesis.json"
  genesis_storage: "/goloop/config/icon_genesis.zip"
  icon2: null
  iiss: null
  iiss_json: "/goloop/icon_config.json"
reference:
  env:
    SERVICE:
      type: "str"
      default: ""
    CID:
      type: "str"
      default: "0x1"
    NID:
      type: "str"
      default: "0x1"
    ROLE:
      type: "int"
      default: 0
    BASE_DIR:
      type: "str"
      default: "/goloop"
    CC_DEBUG:
      type: "bool"
      default: false
    DOCKER_LOG_FILES:
      type: "str"
      default: "chain.log,health.log,error.log,debug.log"
    DOCKER_LOG_STDOUT:
      type: "bool"
      default: false
    CONFIG_LOCAL_FILE:
      type: "str"
      default: "/goloop/configure.yml"
    CONFIG_URL:
      type: "str"
      default: "https://networkinfo.solidwallet.io/icon2"
    CONFIG_URL_FILE:
      type: "str"
      default: "default_configure.yml"
    DOWNLOAD_FORCE:
      type: "bool"
      default: true
    DOWNLOAD_TOOL:
      type: "str"
      default: "aria2c"
    DOWNLOAD_URL:
      type: "str"
      default: "https://networkinfo.solidwallet.io/info"
    DOWNLOAD_URL_TYPE:
      type: "str"
      default: "indexing"
    ENDPOINT:
      type: "str"
      default: "https://preps.net.solidwallet.io"
    FASTEST_START:
      type: "bool"
      default: false
    IS_AUTOGEN_CERT:
      type: "bool"
      default: false
    IS_MIGRATION:
      type: "bool"
      default: false
    KEY_RESET:
      type: "bool"
      default: false
    KEY_PASSWORD:
      type: "str"
      default: "password123!@#"
    KEY_STORE_FILENAME:
      type: "str"
      default: "keystore.json"
    LOGDIR:
      type: "str"
      default: "/goloop/logs"
    LOGFILE:
      type: "str"
      default: "/goloop/logs/goloop.log"
    LOGROTATE_DATE:
      type: "int"
      default: 14
    LOGROTATE_SIZE:
      type: "str"
      default: "1G"
    LOG_OUTPUT_TYPE:
      type: "str"
      default: "file"
    MAIN_TIME_OUT:
      type: "int"
      default: 30
    MAIN_TIME_SLEEP:
      type: "int"
      default: 1
    MAIN_RETRY_COUNT:
      type: "int"
      default: 200
    MIGRATION_START:
      type: "bool"
      default: false
    MIG_INFO_FILE:
      type: "str"
      default: "migration_configure.yml"
    CHECK_BLOCK_STACK:
      type: "int"
      default: 10
    CHECK_PEER_STACK:
      type: "int"
      default: 6
    CHECK_STACK_LIMIT:
      type: "int"
      default: 360
    CHECK_INTERVAL:
      type: "int"
      default: 10
    CHECK_TIMEOUT:
      type: "int"
      default: 10
    NTP_REFRESH_TIME:
      type: "int"
      default: 180
    NTP_SERVER:
      type: "str"
      default: ""
    NTP_SERVERS:
      type: "str"
      default: "time.google.com,time.cloudflare.com,time.facebook.com,time.apple.com,time.euro.apple.com"
    RESTORE_PATH:
      type: "str"
      default: "restore"
    RPC_INCLUDE_DEBUG:
      type: "bool"
      default: false
    AUTO_SEEDS:
      type: "bool"
      default: false
    SEEDS:
      type: "str"
      default: ""
    SLACK_WH_URL:
      type: "str"
      default: ""
  genesis:
    type: "obj"
    default: ""
  iiss:
    type: "obj"
    default: ""
  icon2:
    CPU_PROFILE:
      type: "str"
      default: "/goloop/data/cpu.profile"
    GOLOOP_BACKUP_DIR:
      type: "str"
      default: "/goloop/data/backup"
    GOLOOP_CONFIG:
      type: "str"
      default: "/goloop/config/config.json"
    GOLOOP_CONSOLE_LEVEL:
      type: "str"
      default: "debug"
    GOLOOP_EE_SOCKET:
      type: "str"
      default: "/goloop/data/ee.sock"
    GOLOOP_ENGINES:
      type: "str"
      default: "python"
    GOLOOP_KEY_SECRET:
      type: "str"
      default: "/goloop/config/keysecret"
    GOLOOP_KEY_STORE:
      type: "str"
      default: "/goloop/config/keystore.json"
    GOLOOP_LICENSE_FILE:
      type: "str"
      default: "/goloop/config/license.json"
    GOLOOP_LOG_LEVEL:
      type: "str"
      default: "debug"
    GOLOOP_LOG_WRITER_COMPRESS:
      type: "bool"
      default: false
    GOLOOP_LOG_WRITER_FILENAME:
      type: "str"
      default: "/goloop/logs/goloop.log"
    GOLOOP_LOG_WRITER_LOCALTIME:
      type: "bool"
      default: false
    GOLOOP_LOG_WRITER_MAXAGE:
      type: "int"
      default: 0
    GOLOOP_LOG_WRITER_MAXBACKUPS:
      type: "int"
      default: 0
    GOLOOP_LOG_WRITER_MAXSIZE:
      type: "int"
      default: 100
    GOLOOP_NODE_DIR:
      type: "str"
      default: "/goloop/data"
    GOLOOP_NODE_SOCK:
      type: "str"
      default: "/goloop/data/cli.sock"
    GOLOOP_P2P:
      type: "str"
      default: "127.0.0.1:8080"
    GOLOOP_P2P_LISTEN:
      type: "str"
      default: ":8080"
    GOLOOP_RPC_ADDR:
      type: "str"
      default: ":9080"
    GOLOOP_RPC_DUMP:
      type: "bool"
      default: false
    MEM_PROFILE:
      type: "str"
      default: "/goloop/data/mem.profile"
    GOLOOP_KEY_PLUGIN:
      type: "str"
      default: ""
    GOLOOP_KEY_PLUGIN_OPTIONS:
      type: "str"
      default: ""
    GOLOOP_LOG_FORWARDER_ADDRESS:
      type: "str"
      default: ""
    GOLOOP_LOG_FORWARDER_LEVEL:
      type: "str"
      default: ""
    GOLOOP_LOG_FORWARDER_NAME:
      type: "str"
      default: ""
    GOLOOP_LOG_FORWARDER_VENDOR:
      type: "str"
      default: ""