name: Network Info

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
  aws_bucket: ${{ secrets.AWS_BUCKET }}
  aws_cf_id: ${{ secrets.AWS_CF_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Make the configuration and upload
        run:
          pip3 install -r requirements.txt
          python3 main.py

      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          message: 'Update the Network Configuration'
          ref: 'gh-pages'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          branch: ${{ github.ref }}
